org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true

modgroup=tech.muddykat.engineered_schematics
modarchivename=EngineeredSchematics
mod_id=engineered_schematics
mod_name=Engineered Schematics
mod_authors=Muddykat
mod_description=A mod designed to assist in the building of multiblock structures in a more streamlined manner.
mod_url=https://github.com/tgstyle/engineered_schematics
